#!/bin/bash

EXEC=./prog
INPUT=./$1
OUTPUT=./$2

if [ -z $1 ]; then
	INPUT=./entrada
fi

if [ -z $2 ]; then
	OUTPUT=./saida.py
fi

make 

$EXEC <$INPUT >$OUTPUT

for line in $(cat $OUTPUT); do
	break;
done

if [ $line = "Error:" ]; then
	cat $OUTPUT
else
	echo "Compilacao realizada com sucesso"
fi
