#!/bin/bash

EXEC=/home/parley/Repositorio/Compiladores/prog
INPUT=/home/parley/Repositorio/Compiladores/entrada
OUTPUT=/home/parley/Repositorio/Compiladores/saida.py

make 

$EXEC <$INPUT >$OUTPUT

for line in $(cat $OUTPUT); do
	break;
done

if [ $line = "Error:" ]; then
	cat $OUTPUT
else
	echo "Compilacao realizada com sucesso"
fi
