#!/bin/bash

EXEC=./prog
INPUT=./$1
OUTPUT=./$2.py

make 

if [ -z $1 ]; then
	INPUT=./entrada
fi

if [ -z $2 ]; then
	OUTPUT=./saida.py
fi

if [ $3 ]; then
	shift 2
fi

$EXEC $* <$INPUT >$OUTPUT

for line in $(cat $OUTPUT); do
	break;
done

if [ $line = "Error:" ]; then
	cat $OUTPUT
else
	echo "Compilacao realizada com sucesso"
fi
